
name: Create release draft

# Trigger
on:
  milestone:
    types: [closed]
    
# Action
jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - name: Create milestone release
        id: create-release-milestone
        uses: ecampidoglio/auto-release-milestone@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
